webtalk_init -webtalk_dir /home/jason/Desktop/acc_ip/yolo/yolo.sim/sim_1/behav/xsim/xsim.dir/tb_Conv_acc_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Aug 18 04:34:27 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "715770bf-055d-4ed3-9776-e7a06faafc90" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6477490301b94069800327c7fb88882b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800H with Radeon Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3193.997 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "8" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "310 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126140_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3505702961 -regid "" -xml /home/jason/Desktop/acc_ip/yolo/yolo.sim/sim_1/behav/xsim/xsim.dir/tb_Conv_acc_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jason/Desktop/acc_ip/yolo/yolo.sim/sim_1/behav/xsim/xsim.dir/tb_Conv_acc_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jason/Desktop/acc_ip/yolo/yolo.sim/sim_1/behav/xsim/xsim.dir/tb_Conv_acc_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
